# Generated by Django 6.0.2 on 2026-03-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_12_months',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_3_months',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_6_months',
            field=models.IntegerField(default=15),
        ),
    ]
