# Generated by Django 6.0.2 on 2026-03-06 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriptionplan_discount_12_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount_kobo', models.IntegerField()),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro')], max_length=20)),
                ('months', models.IntegerField(default=1)),
                ('is_renewal', models.BooleanField(default=False)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.client')),
            ],
            options={
                'db_table': 'payment_logs',
                'ordering': ['-paid_at'],
            },
        ),
    ]
