# Generated by Django 6.0.2 on 2026-03-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('critical', 'Critical')], default='error', max_length=20)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('exception_type', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='core.client')),
            ],
            options={
                'db_table': 'error_logs',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
